name: Matrix Demo

on:
  push:
    branches:
      - "**"

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Set matrix data
        id: set-matrix
        run: echo "matrix=$(jq -c < ./test.json)" >> $GITHUB_OUTPUT

  print:
    runs-on: ubuntu-latest
    needs: configure
    environment: ${{ matrix.env }}
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - run: |
          echo "Item: ${{ matrix.item }}"
          echo "Colour: ${{ matrix.colour }}"
          echo "Cost: ${{ matrix.cost }}"
          echo "Env var: ${{ env.MY_VAR }}"
